# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/asal/Documents/Programming/3d-lantern

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/asal/Documents/Programming/3d-lantern

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/opt/homebrew/bin/ctest $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/asal/Documents/Programming/3d-lantern/CMakeFiles /Users/asal/Documents/Programming/3d-lantern//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/asal/Documents/Programming/3d-lantern/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named glad

# Build rule for target.
glad: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glad
.PHONY : glad

# fast build rule for target.
glad/fast:
	$(MAKE) $(MAKESILENT) -f external/CMakeFiles/glad.dir/build.make external/CMakeFiles/glad.dir/build
.PHONY : glad/fast

#=============================================================================
# Target rules for targets named stb_image

# Build rule for target.
stb_image: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 stb_image
.PHONY : stb_image

# fast build rule for target.
stb_image/fast:
	$(MAKE) $(MAKESILENT) -f external/CMakeFiles/stb_image.dir/build.make external/CMakeFiles/stb_image.dir/build
.PHONY : stb_image/fast

#=============================================================================
# Target rules for targets named tinyobjloader

# Build rule for target.
tinyobjloader: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tinyobjloader
.PHONY : tinyobjloader

# fast build rule for target.
tinyobjloader/fast:
	$(MAKE) $(MAKESILENT) -f external/CMakeFiles/tinyobjloader.dir/build.make external/CMakeFiles/tinyobjloader.dir/build
.PHONY : tinyobjloader/fast

#=============================================================================
# Target rules for targets named imgui

# Build rule for target.
imgui: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 imgui
.PHONY : imgui

# fast build rule for target.
imgui/fast:
	$(MAKE) $(MAKESILENT) -f external/CMakeFiles/imgui.dir/build.make external/CMakeFiles/imgui.dir/build
.PHONY : imgui/fast

#=============================================================================
# Target rules for targets named assets

# Build rule for target.
assets: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 assets
.PHONY : assets

# fast build rule for target.
assets/fast:
	$(MAKE) $(MAKESILENT) -f src/assets/CMakeFiles/assets.dir/build.make src/assets/CMakeFiles/assets.dir/build
.PHONY : assets/fast

#=============================================================================
# Target rules for targets named modeling

# Build rule for target.
modeling: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 modeling
.PHONY : modeling

# fast build rule for target.
modeling/fast:
	$(MAKE) $(MAKESILENT) -f src/modeling/CMakeFiles/modeling.dir/build.make src/modeling/CMakeFiles/modeling.dir/build
.PHONY : modeling/fast

#=============================================================================
# Target rules for targets named ray_tracer

# Build rule for target.
ray_tracer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ray_tracer
.PHONY : ray_tracer

# fast build rule for target.
ray_tracer/fast:
	$(MAKE) $(MAKESILENT) -f src/ray_tracer/CMakeFiles/ray_tracer.dir/build.make src/ray_tracer/CMakeFiles/ray_tracer.dir/build
.PHONY : ray_tracer/fast

#=============================================================================
# Target rules for targets named interpreter

# Build rule for target.
interpreter: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 interpreter
.PHONY : interpreter

# fast build rule for target.
interpreter/fast:
	$(MAKE) $(MAKESILENT) -f src/interpreter/CMakeFiles/interpreter.dir/build.make src/interpreter/CMakeFiles/interpreter.dir/build
.PHONY : interpreter/fast

#=============================================================================
# Target rules for targets named application

# Build rule for target.
application: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 application
.PHONY : application

# fast build rule for target.
application/fast:
	$(MAKE) $(MAKESILENT) -f src/application/CMakeFiles/application.dir/build.make src/application/CMakeFiles/application.dir/build
.PHONY : application/fast

#=============================================================================
# Target rules for targets named color_test

# Build rule for target.
color_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 color_test
.PHONY : color_test

# fast build rule for target.
color_test/fast:
	$(MAKE) $(MAKESILENT) -f test/math_test/CMakeFiles/color_test.dir/build.make test/math_test/CMakeFiles/color_test.dir/build
.PHONY : color_test/fast

#=============================================================================
# Target rules for targets named interval_test

# Build rule for target.
interval_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 interval_test
.PHONY : interval_test

# fast build rule for target.
interval_test/fast:
	$(MAKE) $(MAKESILENT) -f test/math_test/CMakeFiles/interval_test.dir/build.make test/math_test/CMakeFiles/interval_test.dir/build
.PHONY : interval_test/fast

#=============================================================================
# Target rules for targets named mat4_test

# Build rule for target.
mat4_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mat4_test
.PHONY : mat4_test

# fast build rule for target.
mat4_test/fast:
	$(MAKE) $(MAKESILENT) -f test/math_test/CMakeFiles/mat4_test.dir/build.make test/math_test/CMakeFiles/mat4_test.dir/build
.PHONY : mat4_test/fast

#=============================================================================
# Target rules for targets named point3_test

# Build rule for target.
point3_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 point3_test
.PHONY : point3_test

# fast build rule for target.
point3_test/fast:
	$(MAKE) $(MAKESILENT) -f test/math_test/CMakeFiles/point3_test.dir/build.make test/math_test/CMakeFiles/point3_test.dir/build
.PHONY : point3_test/fast

#=============================================================================
# Target rules for targets named transform_test

# Build rule for target.
transform_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 transform_test
.PHONY : transform_test

# fast build rule for target.
transform_test/fast:
	$(MAKE) $(MAKESILENT) -f test/math_test/CMakeFiles/transform_test.dir/build.make test/math_test/CMakeFiles/transform_test.dir/build
.PHONY : transform_test/fast

#=============================================================================
# Target rules for targets named vec2_test

# Build rule for target.
vec2_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 vec2_test
.PHONY : vec2_test

# fast build rule for target.
vec2_test/fast:
	$(MAKE) $(MAKESILENT) -f test/math_test/CMakeFiles/vec2_test.dir/build.make test/math_test/CMakeFiles/vec2_test.dir/build
.PHONY : vec2_test/fast

#=============================================================================
# Target rules for targets named vec3_test

# Build rule for target.
vec3_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 vec3_test
.PHONY : vec3_test

# fast build rule for target.
vec3_test/fast:
	$(MAKE) $(MAKESILENT) -f test/math_test/CMakeFiles/vec3_test.dir/build.make test/math_test/CMakeFiles/vec3_test.dir/build
.PHONY : vec3_test/fast

#=============================================================================
# Target rules for targets named vec4_test

# Build rule for target.
vec4_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 vec4_test
.PHONY : vec4_test

# fast build rule for target.
vec4_test/fast:
	$(MAKE) $(MAKESILENT) -f test/math_test/CMakeFiles/vec4_test.dir/build.make test/math_test/CMakeFiles/vec4_test.dir/build
.PHONY : vec4_test/fast

#=============================================================================
# Target rules for targets named md_camera_test

# Build rule for target.
md_camera_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 md_camera_test
.PHONY : md_camera_test

# fast build rule for target.
md_camera_test/fast:
	$(MAKE) $(MAKESILENT) -f test/modeling_test/CMakeFiles/md_camera_test.dir/build.make test/modeling_test/CMakeFiles/md_camera_test.dir/build
.PHONY : md_camera_test/fast

#=============================================================================
# Target rules for targets named md_mesh_test

# Build rule for target.
md_mesh_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 md_mesh_test
.PHONY : md_mesh_test

# fast build rule for target.
md_mesh_test/fast:
	$(MAKE) $(MAKESILENT) -f test/modeling_test/CMakeFiles/md_mesh_test.dir/build.make test/modeling_test/CMakeFiles/md_mesh_test.dir/build
.PHONY : md_mesh_test/fast

#=============================================================================
# Target rules for targets named md_serialize_test

# Build rule for target.
md_serialize_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 md_serialize_test
.PHONY : md_serialize_test

# fast build rule for target.
md_serialize_test/fast:
	$(MAKE) $(MAKESILENT) -f test/modeling_test/CMakeFiles/md_serialize_test.dir/build.make test/modeling_test/CMakeFiles/md_serialize_test.dir/build
.PHONY : md_serialize_test/fast

#=============================================================================
# Target rules for targets named rt_camera_test

# Build rule for target.
rt_camera_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 rt_camera_test
.PHONY : rt_camera_test

# fast build rule for target.
rt_camera_test/fast:
	$(MAKE) $(MAKESILENT) -f test/raytracer_test/CMakeFiles/rt_camera_test.dir/build.make test/raytracer_test/CMakeFiles/rt_camera_test.dir/build
.PHONY : rt_camera_test/fast

#=============================================================================
# Target rules for targets named rt_objectlist_test

# Build rule for target.
rt_objectlist_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 rt_objectlist_test
.PHONY : rt_objectlist_test

# fast build rule for target.
rt_objectlist_test/fast:
	$(MAKE) $(MAKESILENT) -f test/raytracer_test/CMakeFiles/rt_objectlist_test.dir/build.make test/raytracer_test/CMakeFiles/rt_objectlist_test.dir/build
.PHONY : rt_objectlist_test/fast

#=============================================================================
# Target rules for targets named rt_renderer_test

# Build rule for target.
rt_renderer_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 rt_renderer_test
.PHONY : rt_renderer_test

# fast build rule for target.
rt_renderer_test/fast:
	$(MAKE) $(MAKESILENT) -f test/raytracer_test/CMakeFiles/rt_renderer_test.dir/build.make test/raytracer_test/CMakeFiles/rt_renderer_test.dir/build
.PHONY : rt_renderer_test/fast

#=============================================================================
# Target rules for targets named rt_sphere_test

# Build rule for target.
rt_sphere_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 rt_sphere_test
.PHONY : rt_sphere_test

# fast build rule for target.
rt_sphere_test/fast:
	$(MAKE) $(MAKESILENT) -f test/raytracer_test/CMakeFiles/rt_sphere_test.dir/build.make test/raytracer_test/CMakeFiles/rt_sphere_test.dir/build
.PHONY : rt_sphere_test/fast

#=============================================================================
# Target rules for targets named application_test

# Build rule for target.
application_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 application_test
.PHONY : application_test

# fast build rule for target.
application_test/fast:
	$(MAKE) $(MAKESILENT) -f test/application_test/CMakeFiles/application_test.dir/build.make test/application_test/CMakeFiles/application_test.dir/build
.PHONY : application_test/fast

#=============================================================================
# Target rules for targets named model_test

# Build rule for target.
model_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 model_test
.PHONY : model_test

# fast build rule for target.
model_test/fast:
	$(MAKE) $(MAKESILENT) -f test/assets_test/CMakeFiles/model_test.dir/build.make test/assets_test/CMakeFiles/model_test.dir/build
.PHONY : model_test/fast

#=============================================================================
# Target rules for targets named lexer_extern_file_test

# Build rule for target.
lexer_extern_file_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lexer_extern_file_test
.PHONY : lexer_extern_file_test

# fast build rule for target.
lexer_extern_file_test/fast:
	$(MAKE) $(MAKESILENT) -f test/interpreter_test/CMakeFiles/lexer_extern_file_test.dir/build.make test/interpreter_test/CMakeFiles/lexer_extern_file_test.dir/build
.PHONY : lexer_extern_file_test/fast

#=============================================================================
# Target rules for targets named lexer_test

# Build rule for target.
lexer_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lexer_test
.PHONY : lexer_test

# fast build rule for target.
lexer_test/fast:
	$(MAKE) $(MAKESILENT) -f test/interpreter_test/CMakeFiles/lexer_test.dir/build.make test/interpreter_test/CMakeFiles/lexer_test.dir/build
.PHONY : lexer_test/fast

#=============================================================================
# Target rules for targets named parsed_scene_log_test

# Build rule for target.
parsed_scene_log_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 parsed_scene_log_test
.PHONY : parsed_scene_log_test

# fast build rule for target.
parsed_scene_log_test/fast:
	$(MAKE) $(MAKESILENT) -f test/interpreter_test/CMakeFiles/parsed_scene_log_test.dir/build.make test/interpreter_test/CMakeFiles/parsed_scene_log_test.dir/build
.PHONY : parsed_scene_log_test/fast

#=============================================================================
# Target rules for targets named boxes

# Build rule for target.
boxes: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 boxes
.PHONY : boxes

# fast build rule for target.
boxes/fast:
	$(MAKE) $(MAKESILENT) -f example/CMakeFiles/boxes.dir/build.make example/CMakeFiles/boxes.dir/build
.PHONY : boxes/fast

#=============================================================================
# Target rules for targets named clouds

# Build rule for target.
clouds: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clouds
.PHONY : clouds

# fast build rule for target.
clouds/fast:
	$(MAKE) $(MAKESILENT) -f example/CMakeFiles/clouds.dir/build.make example/CMakeFiles/clouds.dir/build
.PHONY : clouds/fast

#=============================================================================
# Target rules for targets named mirror

# Build rule for target.
mirror: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mirror
.PHONY : mirror

# fast build rule for target.
mirror/fast:
	$(MAKE) $(MAKESILENT) -f example/CMakeFiles/mirror.dir/build.make example/CMakeFiles/mirror.dir/build
.PHONY : mirror/fast

#=============================================================================
# Target rules for targets named mirror_chamber

# Build rule for target.
mirror_chamber: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mirror_chamber
.PHONY : mirror_chamber

# fast build rule for target.
mirror_chamber/fast:
	$(MAKE) $(MAKESILENT) -f example/CMakeFiles/mirror_chamber.dir/build.make example/CMakeFiles/mirror_chamber.dir/build
.PHONY : mirror_chamber/fast

#=============================================================================
# Target rules for targets named perlin_scene

# Build rule for target.
perlin_scene: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 perlin_scene
.PHONY : perlin_scene

# fast build rule for target.
perlin_scene/fast:
	$(MAKE) $(MAKESILENT) -f example/CMakeFiles/perlin_scene.dir/build.make example/CMakeFiles/perlin_scene.dir/build
.PHONY : perlin_scene/fast

#=============================================================================
# Target rules for targets named planar

# Build rule for target.
planar: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 planar
.PHONY : planar

# fast build rule for target.
planar/fast:
	$(MAKE) $(MAKESILENT) -f example/CMakeFiles/planar.dir/build.make example/CMakeFiles/planar.dir/build
.PHONY : planar/fast

#=============================================================================
# Target rules for targets named sphere_cylindre_cone

# Build rule for target.
sphere_cylindre_cone: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sphere_cylindre_cone
.PHONY : sphere_cylindre_cone

# fast build rule for target.
sphere_cylindre_cone/fast:
	$(MAKE) $(MAKESILENT) -f example/CMakeFiles/sphere_cylindre_cone.dir/build.make example/CMakeFiles/sphere_cylindre_cone.dir/build
.PHONY : sphere_cylindre_cone/fast

#=============================================================================
# Target rules for targets named teapot

# Build rule for target.
teapot: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 teapot
.PHONY : teapot

# fast build rule for target.
teapot/fast:
	$(MAKE) $(MAKESILENT) -f example/CMakeFiles/teapot.dir/build.make example/CMakeFiles/teapot.dir/build
.PHONY : teapot/fast

#=============================================================================
# Target rules for targets named transforms_showcase

# Build rule for target.
transforms_showcase: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 transforms_showcase
.PHONY : transforms_showcase

# fast build rule for target.
transforms_showcase/fast:
	$(MAKE) $(MAKESILENT) -f example/CMakeFiles/transforms_showcase.dir/build.make example/CMakeFiles/transforms_showcase.dir/build
.PHONY : transforms_showcase/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... application"
	@echo "... application_test"
	@echo "... assets"
	@echo "... boxes"
	@echo "... clouds"
	@echo "... color_test"
	@echo "... glad"
	@echo "... imgui"
	@echo "... interpreter"
	@echo "... interval_test"
	@echo "... lexer_extern_file_test"
	@echo "... lexer_test"
	@echo "... mat4_test"
	@echo "... md_camera_test"
	@echo "... md_mesh_test"
	@echo "... md_serialize_test"
	@echo "... mirror"
	@echo "... mirror_chamber"
	@echo "... model_test"
	@echo "... modeling"
	@echo "... parsed_scene_log_test"
	@echo "... perlin_scene"
	@echo "... planar"
	@echo "... point3_test"
	@echo "... ray_tracer"
	@echo "... rt_camera_test"
	@echo "... rt_objectlist_test"
	@echo "... rt_renderer_test"
	@echo "... rt_sphere_test"
	@echo "... sphere_cylindre_cone"
	@echo "... stb_image"
	@echo "... teapot"
	@echo "... tinyobjloader"
	@echo "... transform_test"
	@echo "... transforms_showcase"
	@echo "... vec2_test"
	@echo "... vec3_test"
	@echo "... vec4_test"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

